
(() => {
  'use strict';
  const money = n => Number.isFinite(n) ? new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n) : 'Not available';
  const money2 = n => Number.isFinite(n) ? new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n) : 'Not available';
  const pct = n => Number.isFinite(n) ? `${n.toFixed(1)}%` : 'Not available';
  const num = id => Number(document.getElementById(id)?.value);
  const finiteNonnegative = id => { const v=num(id); return Number.isFinite(v)&&v>=0; };
  const yearsToMonths = n => Math.max(1, Math.round(n*12));
  const pmt = (principal, annualRate, months) => { if(![principal,annualRate,months].every(Number.isFinite)||principal<0||annualRate<0||months<1)return NaN; if(principal===0)return 0; const r=annualRate/1200; return r===0?principal/months:principal*r/(1-Math.pow(1+r,-months)); };
  const remaining = (principal, annualRate, payment, monthsPaid) => { if(![principal,annualRate,payment,monthsPaid].every(Number.isFinite)||principal<0||annualRate<0||payment<0||monthsPaid<0)return NaN; let bal=principal, r=annualRate/1200; for(let i=0;i<Math.floor(monthsPaid)&&bal>0;i++){let interest=bal*r; bal=Math.max(0,bal+interest-payment); if(payment<=interest&&bal>0)return NaN;} return bal; };
  const show = (id, html) => { const el=document.getElementById(id); if(el){el.innerHTML=html;el.hidden=false;} };
  const error = (id,msg) => { const el=document.getElementById(id); if(el)el.textContent=msg; };
  const clearError = id => error(id,'');
  const track = (event, params={}) => { if(typeof window.gtag==='function') window.gtag('event',event,{tool_category:document.body.dataset.tool||'fintech',...params}); };
  const link_block = (items) => `<div class="tv-fintech-list-links">${items.map(([href,label])=>`<a href="${href}">${label}</a>`).join('')}</div>`;

  function debt(){
    const form=document.getElementById('debt-form'); if(!form)return;
    const ids=['d1-balance','d1-apr','d1-min','d2-balance','d2-apr','d2-min','d3-balance','d3-apr','d3-min','available-payment','consolidation-apr','consolidation-term','origination-fee','settlement-pct','program-fee','delinquency-months'];
    form.addEventListener('submit',e=>{e.preventDefault();clearError('debt-error'); if(ids.some(id=>!finiteNonnegative(id))){error('debt-error','Enter zero or greater values in every field.');return;} const debts=[0,1,2].map(i=>({b:num(`d${i+1}-balance`),a:num(`d${i+1}-apr`),m:num(`d${i+1}-min`)})).filter(d=>d.b>0); const available=num('available-payment'); const total=debts.reduce((s,d)=>s+d.b,0); if(total<=0||available<=0){error('debt-error','Enter at least one balance and a positive monthly payment.');return;} const currentMin=debts.reduce((s,d)=>s+d.m,0); const currentPayment=Math.max(currentMin,available); const weighted=debts.reduce((s,d)=>s+d.b*d.a,0)/total; const currentMonths=Math.ceil(total/Math.max(1,currentPayment-weighted/1200*total)); const currentInterest=Math.max(0,currentPayment*currentMonths-total);
      const conFee=total*num('origination-fee')/100; const conPmt=pmt(total+conFee,num('consolidation-apr'),yearsToMonths(num('consolidation-term'))); const conTotal=conPmt*yearsToMonths(num('consolidation-term')); const conInterest=Math.max(0,conTotal-total-conFee); const settleBase=total*num('settlement-pct')/100; const settleFee=settleBase*num('program-fee')/100; const settleTotal=settleBase+settleFee; const settleMonths=Math.ceil(settleTotal/available)+num('delinquency-months'); const conSavings=currentInterest-conInterest-conFee;
      show('debt-result',`<h3>Compare the planning scenarios</h3><div class="tv-fintech-metrics"><div class="tv-fintech-metric"><span>Total unsecured debt</span><strong>${money(total)}</strong></div><div class="tv-fintech-metric"><span>Consolidation payment</span><strong>${money2(conPmt)}/mo</strong></div><div class="tv-fintech-metric"><span>Consolidation interest + fee</span><strong>${money(conInterest+conFee)}</strong></div><div class="tv-fintech-metric"><span>Estimated settlement amount + fee</span><strong>${money(settleTotal)}</strong></div><div class="tv-fintech-metric"><span>Estimated consolidation difference</span><strong>${money(conSavings)}</strong></div><div class="tv-fintech-metric"><span>Estimated settlement timeline</span><strong>${settleMonths} months</strong></div></div><p class="tv-fintech-note">The consolidation figure assumes the proposed rate, fee, and term. The settlement figure is only a scenario: creditors may refuse, fees vary, delinquency can damage credit, and forgiven debt may have tax consequences. A positive difference is not guaranteed savings.</p><p class="tv-fintech-note">Current-payment comparison uses a simplified blended estimate; an actual avalanche schedule depends on each creditor’s rules and payment allocation.</p>`);track('calculator_completed',{result_category:conSavings>0?'consolidation_may_cost_less':'compare_total_costs'});
    }); track('calculator_started');
  }

  function auto(){
    const form=document.getElementById('auto-form'); if(!form)return;
    form.addEventListener('submit',e=>{e.preventDefault();clearError('auto-error'); const ids=['auto-balance','auto-apr','auto-remaining','auto-payment','auto-value','auto-new-apr','auto-new-term','auto-fees','auto-cash-down']; if(ids.some(id=>!finiteNonnegative(id))||num('auto-remaining')<1||num('auto-new-term')<1){error('auto-error','Enter valid nonnegative values and at least one month for each term.');return;} const bal=num('auto-balance'), oldApr=num('auto-apr'), rem=Math.round(num('auto-remaining')), oldPay=num('auto-payment'), value=num('auto-value'), newApr=num('auto-new-apr'), newMonths=Math.round(num('auto-new-term')*12), fees=num('auto-fees'), down=num('auto-cash-down'); const oldInterest=Math.max(0,oldPay*rem-bal); const newPrincipal=Math.max(0,bal-down)+fees; const newPay=pmt(newPrincipal,newApr,newMonths); const newInterest=Math.max(0,newPay*newMonths-newPrincipal); const totalDiff=oldInterest-(newInterest+fees); const monthlyDiff=oldPay-newPay; const breakEven=monthlyDiff>0?Math.ceil(fees/monthlyDiff):Infinity; const ltv=value>0?bal/value*100:NaN; const neg=Math.max(0,bal-value); show('auto-result',`<h3>Refinance trade-off</h3><div class="tv-fintech-metrics"><div class="tv-fintech-metric"><span>Current remaining interest</span><strong>${money(oldInterest)}</strong></div><div class="tv-fintech-metric"><span>New payment</span><strong>${money2(newPay)}/mo</strong></div><div class="tv-fintech-metric"><span>New estimated interest</span><strong>${money(newInterest)}</strong></div><div class="tv-fintech-metric"><span>Estimated total-cost change</span><strong>${money(totalDiff)}</strong></div><div class="tv-fintech-metric"><span>Loan-to-value</span><strong>${pct(ltv)}</strong></div><div class="tv-fintech-metric"><span>Negative equity</span><strong>${money(neg)}</strong></div></div><p class="tv-fintech-note">${monthlyDiff>0?`The payment could fall by ${money2(monthlyDiff)} per month.`:'The proposed refinance does not lower the monthly payment.'} ${Number.isFinite(breakEven)?`The fee break-even point is about month ${breakEven}.`:'There is no payment-based fee break-even because the new payment is not lower.'} A lower payment can still cost more overall when a term is extended.</p>`);track('calculator_completed',{result_category:totalDiff>=0?'lower_estimated_total_cost':'lower_payment_not_total_cost'});}); track('calculator_started');
  }

  function tax(){
    const form=document.getElementById('tax-form'); if(!form)return;
    form.addEventListener('submit',e=>{e.preventDefault();clearError('tax-error'); const ids=['tax-wages','tax-withheld','tax-periods','tax-spouse-income','tax-spouse-withheld','tax-untaxed','tax-adjustments','tax-deduction','tax-credits','tax-prior-tax']; if(ids.some(id=>!finiteNonnegative(id))||num('tax-periods')<1){error('tax-error','Enter zero or greater values and at least one remaining pay period.');return;} const status=document.getElementById('tax-status').value; const wages=num('tax-wages')+num('tax-spouse-income')+num('tax-untaxed'); const deduction=num('tax-deduction')||({single:16100,'married-joint':32200,'head-household':24150}[status]||16100); const taxable=Math.max(0,wages-num('tax-adjustments')-deduction); const brackets=status==='married-joint'?[[24800,.1],[100800,.12],[211400,.22],[403550,.24],[512450,.32],[768700,.35],[Infinity,.37]]:[[12400,.1],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[640600,.35],[Infinity,.37]]; let tax=0,prev=0; for(const [limit,rate] of brackets){const slice=Math.max(0,Math.min(taxable,limit)-prev);tax+=slice*rate;prev=limit;if(taxable<=limit)break;} tax=Math.max(0,tax-num('tax-credits')); const paid=num('tax-withheld')+num('tax-spouse-withheld'); const due=tax-paid; const perPay=due>0?due/num('tax-periods'):0; const prior=num('tax-prior-tax'); const safeHarbor=prior>0?paid>=prior*.9||paid>=tax*.9:false; show('tax-result',`<h3>Projected federal withholding gap</h3><div class="tv-fintech-metrics"><div class="tv-fintech-metric"><span>Estimated taxable income</span><strong>${money(taxable)}</strong></div><div class="tv-fintech-metric"><span>Projected federal tax</span><strong>${money(tax)}</strong></div><div class="tv-fintech-metric"><span>Projected payments</span><strong>${money(paid)}</strong></div><div class="tv-fintech-metric"><span>Estimated ${due>=0?'amount due':'refund'}</span><strong>${money(Math.abs(due))}</strong></div><div class="tv-fintech-metric"><span>Additional per remaining paycheck</span><strong>${money2(perPay)}</strong></div><div class="tv-fintech-metric"><span>Basic safe-harbor screen</span><strong>${safeHarbor?'May pass':'Review with IRS guidance'}</strong></div></div><p class="tv-fintech-note">This is a simplified 2026 planning estimate using the selected filing status, deduction, brackets, credits, and entered withholding. It is not a completed Form W-4, tax return, or tax advice. Verify with the official <a href="https://www.irs.gov/individuals/tax-withholding-estimator">IRS Tax Withholding Estimator</a>.</p>`);track('calculator_completed',{result_category:due>0?'projected_balance_due':'projected_refund'});}); track('calculator_started');
  }

  function aca(){
    const form=document.getElementById('aca-form'); if(!form)return;
    form.addEventListener('submit',e=>{e.preventDefault();clearError('aca-error'); const ids=['aca-gross','aca-credit','aca-deductible','aca-oop','aca-use']; if(ids.some(id=>!finiteNonnegative(id))){error('aca-error','Enter zero or greater values in every field.');return;} const gross=num('aca-gross'),credit=num('aca-credit'),ded=num('aca-deductible'),oop=num('aca-oop'),use=num('aca-use'); const net=Math.max(0,gross-credit), annualPremium=net*12, expected=Math.min(oop,use*.25), total=annualPremium+expected; show('aca-result',`<h3>Estimated annual coverage cost</h3><div class="tv-fintech-metrics"><div class="tv-fintech-metric"><span>Estimated net monthly premium</span><strong>${money(net)}</strong></div><div class="tv-fintech-metric"><span>Estimated net annual premium</span><strong>${money(annualPremium)}</strong></div><div class="tv-fintech-metric"><span>Deductible entered</span><strong>${money(ded)}</strong></div><div class="tv-fintech-metric"><span>Expected-care exposure</span><strong>${money(expected)}</strong></div><div class="tv-fintech-metric"><span>Planning total</span><strong>${money(total)}</strong></div><div class="tv-fintech-metric"><span>Maximum out-of-pocket entered</span><strong>${money(oop)}</strong></div></div><p class="tv-fintech-note">The expected-care scenario uses one simple utilization assumption and is not a forecast. Premium Tax Credit eligibility and official plan costs are determined by the Marketplace. Verify plans at <a href="https://www.healthcare.gov/see-plans/">HealthCare.gov</a> or your state Marketplace.</p>`);track('calculator_completed',{result_category:'aca_total_cost_estimate'});}); track('calculator_started');
  }

  function credit(){
    const form=document.getElementById('credit-form'); if(!form)return;
    form.addEventListener('submit',e=>{e.preventDefault();clearError('credit-error'); const ids=['c1-balance','c1-limit','c1-apr','c2-balance','c2-limit','c2-apr','c3-balance','c3-limit','c3-apr','credit-target','credit-payment']; if(ids.some(id=>!finiteNonnegative(id))||num('credit-target')>100||num('credit-payment')<=0){error('credit-error','Enter valid balances, limits, rates, a target up to 100%, and a positive payment.');return;} const cards=[1,2,3].map(i=>({b:num(`c${i}-balance`),l:num(`c${i}-limit`),a:num(`c${i}-apr`)})); const bal=cards.reduce((s,c)=>s+c.b,0), lim=cards.reduce((s,c)=>s+c.l,0), util=lim>0?bal/lim*100:NaN, target=num('credit-target'), targetBal=lim*target/100, required=Math.max(0,bal-targetBal), pay=num('credit-payment'), months=required===0?0:Math.ceil(required/pay), interest=cards.reduce((s,c)=>s+c.b*c.a/100/12,0); show('credit-result',`<h3>Utilization and interest-cost view</h3><div class="tv-fintech-metrics"><div class="tv-fintech-metric"><span>Overall utilization</span><strong>${pct(util)}</strong></div><div class="tv-fintech-metric"><span>Balance to reach target</span><strong>${money(required)}</strong></div><div class="tv-fintech-metric"><span>Estimated months at entered payment</span><strong>${months}</strong></div><div class="tv-fintech-metric"><span>Approx. monthly interest at current balances</span><strong>${money2(interest)}</strong></div></div><p class="tv-fintech-note">Utilization is reported balances divided by total credit limits. Paying down balances can change reported utilization, but no tool can promise a credit-score increase. Issuers’ statement dates and scoring models matter. DTI is a separate measure and is not inferred here.</p>`);track('calculator_completed',{result_category:util<=target?'at_or_below_target':'paydown_needed'});}); track('calculator_started');
  }

  function mortgage(){
    const form=document.getElementById('mortgage-form'); if(!form)return;
    form.addEventListener('submit',e=>{e.preventDefault();clearError('mortgage-error'); const ids=['m-balance','m-apr','m-remaining','m-new-apr','m-new-term','m-costs','m-points','m-time-home']; if(ids.some(id=>!finiteNonnegative(id))||num('m-remaining')<1||num('m-new-term')<1||num('m-time-home')<0){error('mortgage-error','Enter valid nonnegative values and positive terms.');return;} const bal=num('m-balance'), oldPay=pmt(bal,num('m-apr'),Math.round(num('m-remaining'))), oldInterest=oldPay*num('m-remaining')-bal, costs=num('m-costs')+bal*num('m-points')/100, newPay=pmt(bal,num('m-new-apr'),yearsToMonths(num('m-new-term'))), newInterest=newPay*yearsToMonths(num('m-new-term'))-bal, monthly=oldPay-newPay, breakEven=monthly>0?Math.ceil(costs/monthly):Infinity, horizon=Math.min(yearsToMonths(num('m-time-home')),yearsToMonths(num('m-new-term'))), horizonBenefit=monthly*horizon-costs; show('mortgage-result',`<h3>Refinance break-even view</h3><div class="tv-fintech-metrics"><div class="tv-fintech-metric"><span>Current payment</span><strong>${money2(oldPay)}/mo</strong></div><div class="tv-fintech-metric"><span>New payment</span><strong>${money2(newPay)}/mo</strong></div><div class="tv-fintech-metric"><span>Current remaining interest</span><strong>${money(oldInterest)}</strong></div><div class="tv-fintech-metric"><span>New scheduled interest</span><strong>${money(newInterest)}</strong></div><div class="tv-fintech-metric"><span>Break-even month</span><strong>${Number.isFinite(breakEven)?breakEven:'No payment break-even'}</strong></div><div class="tv-fintech-metric"><span>Estimated benefit over planned horizon</span><strong>${money(horizonBenefit)}</strong></div></div><p class="tv-fintech-note">A longer replacement term can lower payment while restarting interest and increasing total interest. This screen does not model taxes, insurance, escrow, prepayment penalties, credit pricing, or cash-out risk. Compare the result with your intended time in the home.</p>`);track('calculator_completed',{result_category:horizonBenefit>=0?'break_even_may_fit_horizon':'costs_may_exceed_horizon'});}); track('calculator_started');
  }

  function emergency(){
    const form=document.getElementById('emergency-form'); if(!form)return;
    form.addEventListener('submit',e=>{e.preventDefault();clearError('emergency-error'); const ids=['ef-savings','ef-essential','ef-income','ef-debt','ef-target-months','ef-monthly-save']; if(ids.some(id=>!finiteNonnegative(id))||num('ef-essential')<=0){error('emergency-error','Enter savings, income, debt, savings rate, and positive essential expenses.');return;} const savings=num('ef-savings'), essential=num('ef-essential'), income=num('ef-income'), debt=num('ef-debt'), target=num('ef-target-months'), monthlySave=num('ef-monthly-save'), runway=savings/essential, deficit=Math.max(0,essential+debt-income), needed=Math.max(0,essential*target-savings), months=needed===0?0:monthlySave>0?Math.ceil(needed/monthlySave):Infinity; show('emergency-result',`<h3>Emergency runway and income-shock view</h3><div class="tv-fintech-metrics"><div class="tv-fintech-metric"><span>Current runway</span><strong>${runway.toFixed(1)} months</strong></div><div class="tv-fintech-metric"><span>Monthly income-shock deficit</span><strong>${money(deficit)}</strong></div><div class="tv-fintech-metric"><span>Savings needed for target</span><strong>${money(needed)}</strong></div><div class="tv-fintech-metric"><span>Time to target at entered savings</span><strong>${Number.isFinite(months)?months:'Not reached'}</strong></div></div><p class="tv-fintech-note">Runway uses liquid savings divided by essential expenses. It is a planning scenario, not a promise about job-loss duration or benefits. If cash flow is distressed, review neutral steps such as expense triage, payment hardship options, public resources, and trusted advice before considering new borrowing.</p>`);track('calculator_completed',{result_category:runway>=target?'target_reached':'build_runway'});}); track('calculator_started');
  }
  debt();auto();tax();aca();credit();mortgage();emergency();
})();
